export enum Messages {
	OBJECT_POSITION = 'OBJECT_POSITION',
	OBJECT_DESTROYED = 'OBJECT_DESTROYED',
	COLLISION = 'COLLISION',
	COLLISION_END = 'COLLISION_END',

	FREEZE = 'FREEZE',
	UNFREEZE = 'UNFREEZE',

	PLAYER_RESET = 'PLAYER_RESET',
	FLIP_GRAVITY = 'FLIP_GRAVITY',
	FLIP_IMAGE = 'FLIP_IMAGE',

	BUFF = 'BUFF',
	LOAD_CHECKPOINT = 'LOAD_CHECKPOINT',
	SAVE_CHECKPOINT = 'SAVE_CHECKPOINT',

	PLAYER_DIRECTION = 'PLAYER_DIRECTION',

	SLOW_MOTION_START = 'SLOW_MOTION_START',
	SLOW_MOTION_END = 'SLOW_MOTION_END',
	MODIFY_SPEED = 'MODIFY_SPEED',

	START_GAME = 'START_GAME',
    END_GAME = 'END_GAME',

    SPAWN_BLOCK = 'SPAWN_BLOCK'
}