export enum Messages {
	OBJECT_POSITION = 'OBJECT_POSITION',
	OBJECT_DESTROYED = 'OBJECT_DESTROYED',
	COLLISION = 'COLLISION',
	COLLISION_END = 'COLLISION_END',

/*	COLLISION_TOP = 'COLLISION_TOP',
	COLLISION_TOP_END = 'COLLISION_TOP_END',
	COLLISION_BOT = 'COLLISION_BOT',
	COLLISION_BOT_END = 'COLLISION_BOT_END',
	COLLISION_LEFT = 'COLLISION_LEFT',
	COLLISION_LEFT_END = 'COLLISION_LEFT_END',
	COLLISION_RIGHT = 'COLLISION_RIGHT',
	COLLISION_RIGHT_END = 'COLLISION_TOP_RIGHT',*/

	FREEZE = 'FREEZE',
	UNFREEZE = 'UNFREEZE',

	PLAYER_RESET = 'PLAYER_RESET',
	FLIP_GRAVITY = 'FLIP',

	BUFF = 'BUFF',
	LOAD_CHECKPOINT = 'LOAD_CHECKPOINT',
	SAVE_CHECKPOINT = 'SAVE_CHECKPOINT',

    PLAYER_DIRECTION = 'PLAYER_DIRECTION',

    SLOW_MOTION_START = 'SLOW_MOTION_START',   
    SLOW_MOTION_END = 'SLOW_MOTION_END'
}